#!/bin/sh
USERS=$(lslogins --noheadings -u -o user | grep -vw root)

# add keys to pubkeyring for iso verification and alerts messages
for USER in $USERS
do
	  cmd="/usr/bin/gpg --import /usr/share/mx-gpg-keys/*.asc"
      runuser $USER -c "$cmd" 2>/dev/null ||exit 0
done

exit 0
